[workspace]
#members = [ "apps", "octets", "qlog", "quiche" ]
members = [ "octets", "qlog", "quiche" ]
exclude = [ "fuzz", "tools/http3_test" ]

[profile.bench]
debug = true

[profile.release]
debug = true
